services:
  # --- 1. THE SINGLE MYSQL DATABASE ---
  # mysql-db:
  #   image: mysql:8.0
  #   container_name: eventzen-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin # Updated to match your Node config
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     # This runs the script to create both databases on startup
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - mysql_data:/var/lib/mysql # 👈 ADD THIS LINE
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
  #     interval: 5s
  #     timeout: 10s
  #     retries: 10

  # --- 2. SPRING BOOT 1 (User/Auth) ---
  user-auth-api:
    build: ./EventManageUserAPI
    container_name: user-auth-service
    restart: on-failure
    ports:
      - "9000:9000"
    # depends_on:
    #   mysql-db:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limits to exactly half a CPU core
          memory: 512M # Limits to 512MB RAM (Like an AWS t2.micro)
    environment:
      - SERVER_PORT=9000
      - DB_USER=${AIVEN_USER} # Docker grabs this from the .env file
      - DB_PASS=${AIVEN_PASS} # Docker grabs this from the .env file
      # Removed local DB overrides so it safely uses your application.properties!

      # --- 3. SPRING BOOT 2 (Events/Bookings) ---
  events-booking-api:
    build: ./events_bookings_api
    container_name: events-booking-service
    restart: on-failure
    ports:
      - "9002:9002"
    # depends_on:
    #   mysql-db:
    #     condition: service_healthy
    environment:
      - SERVER_PORT=9002
      - DB_USER=${AIVEN_USER} # Docker grabs this from the .env file
      - DB_PASS=${AIVEN_PASS} # Docker grabs this from the .env file
      # Removed local DB overrides so it safely uses your application.properties!
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_URL=${REDIS_URL}
      - SPRING_DATA_REDIS_URL=${REDIS_URL}
      # --- 4. NODE.JS API ---
  venue-vendor-api:
    build: ./VenueAndVendorAPI
    # container_name: venue-vendor-service
    restart: on-failure
    ports:
      - "9001-9005:9001" # Updated port
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limits to exactly half a CPU core
          memory: 512M # Limits to 512MB RAM (Like an AWS t2.micro)
    # depends_on:
    #   mysql-db:
    #     condition: service_healthy
    environment:
      - PORT=9001
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${AIVEN_USER}
      - DB_PASS=${AIVEN_PASS}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_URL=${REDIS_URL}
      # --- 5. FRONTEND ---
      # frontend-app:
      #   build: ./Frontend/manager-sys
      #   container_name: eventzen-frontend
      #   ports:
      #     - "3000:3000" # Changed back to 3000:3000 to match React!
      #   depends_on:
      #     mysql-db:
      #       condition: service_healthy
      #   environment:
      #     # These variables ensure React hot-reloading works perfectly through Windows Docker
      #     - WATCHPACK_POLLING=true
      #     - WDS_SOCKET_PORT=0
      #   volumes:
      #     # This mirrors your live Windows folder into the container
      #     - ./Frontend/manager-sys:/app
      #     # This protects the container's node_modules from being overwritten
      #     - /app/node_modules

      # --- 6. API GATEWAY ---
  api-gateway:
    build: ./gateway # Path to your new gateway folder
    container_name: eventzen-gateway
    ports:
      - "8080:8080" # The ONLY backend port exposed to the outside world
    depends_on:
      - user-auth-api # <-- CHANGED from user-auth-service
      - venue-vendor-api # <-- CHANGED from venue-vendor-service
      - events-booking-api # <-- CHANGED from events-booking-service
  # --- Local RabbitMQ (Commented out since using Cloud RabbitMQ) ---
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq-broker
  #   ports:
  #     - "5672:5672" # The port Java uses to send messages
  #     - "15672:15672" # The port YOU use to see the Web UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: myuser
  #     RABBITMQ_DEFAULT_PASS: mypassword
  # --- 7. REDIS CACHE ---
  #   redis-cache:
  #     image: redis:alpine
  #     container_name: eventzen-redis
  #     ports:
  #       - "6379:6379"

  # volumes:
  #   mysql_data:
