spring.application.name=gateway


server.port=8080

# --- 1. User & Auth Service ---
# Rule for /auth/**
spring.cloud.gateway.mvc.routes[0].id=auth-route
spring.cloud.gateway.mvc.routes[0].uri=http://user-auth-service:9000
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# Rule for /user/**
spring.cloud.gateway.mvc.routes[1].id=user-route
spring.cloud.gateway.mvc.routes[1].uri=http://user-auth-service:9000
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/user/**

# Rule for /api/attendees/**
spring.cloud.gateway.mvc.routes[2].id=attendees-route
spring.cloud.gateway.mvc.routes[2].uri=http://user-auth-service:9000
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/attendees/**

# --- 2. Venue & Vendor Service ---
spring.cloud.gateway.mvc.routes[3].id=venues-route
spring.cloud.gateway.mvc.routes[3].uri=http://venue-vendor-service:9001
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/venues/**

spring.cloud.gateway.mvc.routes[4].id=vendors-route
spring.cloud.gateway.mvc.routes[4].uri=http://venue-vendor-service:9001
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/vendors/**

# --- 3. Events & Booking Service ---
spring.cloud.gateway.mvc.routes[5].id=events-route
spring.cloud.gateway.mvc.routes[5].uri=http://events-booking-service:9002
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/events/**

spring.cloud.gateway.mvc.routes[6].id=bookings-route
spring.cloud.gateway.mvc.routes[6].uri=http://events-booking-service:9002
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/bookings/**

# Reveal exactly how the Gateway routes traffic
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=DEBUG