spring.application.name=EventManageUserAPI
server.port=9002
spring.datasource.url=jdbc:mysql://localhost:3306/events_booking_db
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.override-with-generic-response=false

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq-broker
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=mypassword