spring.application.name=EventManageUserAPI
server.port=9000

# Aiven Cloud MySQL Configuration
spring.datasource.url=jdbc:mysql://eventzen-db-eventzen-db.h.aivencloud.com:26244/userattendeesdb?sslMode=REQUIRED
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keep your safe ORM update rule!
spring.jpa.hibernate.ddl-auto=update

# spring.datasource.url=jdbc:mysql://localhost:3306/userattendeesdb
# spring.datasource.username=root
# spring.datasource.password=admin
spring.jpa.show-sql=true

springdoc.override-with-generic-response=false